### ISSUE TITLE
Is the Test Runner supported in Eclipse Neon.3?

### ISSUE THREAD

**Issue by spruce808** [tcmak/CppUTestEclipseJunoTestRunner#13]
I'm using Eclipse Neon.3 Release (4.6.3). I getting the exception below when I try to invoke the TestRunner. I believe I have installed everything correctly. The unit tests all run and pass when run directly from the command line.

Thanks
Peter

```
Exception in thread "Thread-12" java.lang.StringIndexOutOfBoundsException: String index out of range
: -9
        at java.lang.String.substring(Unknown Source)
        at org.eclipse.cdt.testsrunner.internal.cpputest.CppUTestCaseFactory.getErrorMessage(CppUTes
tCaseFactory.java:98)
        at org.eclipse.cdt.testsrunner.internal.cpputest.CppUTestCaseFactory.createFailedTestcase(Cp
pUTestCaseFactory.java:74)
        at org.eclipse.cdt.testsrunner.internal.cpputest.CppUTestCaseFactory.create(CppUTestCaseFact
ory.java:30)
        at org.eclipse.cdt.testsrunner.internal.cpputest.TestIterator.fetchTest(TestIterator.java:36
)
        at org.eclipse.cdt.testsrunner.internal.cpputest.CppUTestStdOutputParser.parse(CppUTestStdOu
tputParser.java:20)
        at org.eclipse.cdt.testsrunner.internal.cpputest.CppUTestRunnerProvider.run(CppUTestRunnerPr
ovider.java:66)
        at org.eclipse.cdt.testsrunner.internal.model.TestingSession.run(TestingSession.java:192)
        at org.eclipse.cdt.testsrunner.internal.launcher.TestingProcessFactory$TestingSessionRunner.
run(TestingProcessFactory.java:53)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by spruce808** [comment]
I've traced the problem to my test program writing debug messages to stdout. If these are suppressed the TestRunner works fine. I assume the plug-in only supports the output generated by the CppUTest CommandLineTestRunner?
